//
// Created by cheyulin on 7/19/16.
//

#ifndef CODES_YCHE_CONFIGURATION_H
#define CODES_YCHE_CONFIGURATION_H

//#define REDUCE_2ND_PHASE_SEQUENTIAL
//#define NOT_COUT_COMMUNITY_RESULT
//#define STEAL_ENABLE
//#define FINE_GRAINED_REDUCE_ENABLE
//#define DEBUG

#endif //CODES_YCHE_CONFIGURATION_H
