//
// Created by cheyulin on 7/19/16.
//

#ifndef CODES_YCHE_CONFIGURATION_H
#define CODES_YCHE_CONFIGURATION_H

//#define REDUCE_2ND_PHASE_SEQUENTIAL
//#define NOT_COUT_COMMUNITY_RESULT
//#define DEBUG
#define ENABLE_OVERLAP_MERGE_TO_GLOBAL

#endif //CODES_YCHE_CONFIGURATION_H
